version: '3'

services:

  public-node:
    container_name: public-node
    image: legalthings/public-node
    restart: always
    volumes:
      - ./data:/lto/data
    ports:
      - 6869:6869
      - 6868:6868
    environment:
      - LTO_WALLET_SEED=<seed of your wallet>
      - LTO_WALLET_PASSWORD=<a password for your wallet>
      - LTO_API_KEY=<a secret to use the api>
